from typing import Protocol, List, Tuple, Optional, Any

class RepositoryInterface(Protocol):
    def registrar_profesor(self, user_id: int, username: str) -> None: ...
    def verificar_profesor(self, user_id: int) -> None: ...
    def es_profesor_verificado(self, user_id: int) -> bool: ...
    def registrar_grupo(self, chat_id: int, nombre: str, profesor_id: int) -> None: ...
    def obtener_grupos_profesor(self, profesor_id: int) -> List[Tuple[int, str]]: ...
    def obtener_todos_los_grupos(self) -> List[Tuple[int, str]]: ...
    def es_grupo_registrado(self, chat_id: int) -> bool: ...

class AIAdapterInterface(Protocol):
    def estructurar_texto_formal(self, texto: str) -> str: ...
    def transcribir_y_estructurar(self, texto: str) -> str: ...
    def generar_minuta_apa(self, contenido: str, formato: str) -> str: ...
    def interpretar_intencion(self, mensaje: str) -> str: ...
    def detectar_contenido_inapropiado(self, mensaje: str) -> str: ...
    def responder_conversacion(self, mensaje: str, contexto: str = "") -> str: ...
