from typing import Protocol, List, Tuple

class RepositoryInterface(Protocol):
    def registrar_profesor(self, user_id: int, username: str) -> None: ...
    def verificar_profesor(self, user_id: int) -> None: ...
    def es_profesor_verificado(self, user_id: int) -> bool: ...
    def es_estudiante_verificado(self, user_id: int) -> bool: ...
    def registrar_miembro_grupo(self, chat_id: int, user_id: int, first_name: str, last_name: str, username: str) -> None: ...
    def obtener_miembros_grupo(self, chat_id: int) -> List[Tuple]: ...
    def guardar_estudiante_grupo(self, chat_id: int, cedula: str, apellidos: str, nombres: str, correo: str) -> None: ...
    def obtener_estudiantes_grupo(self, chat_id: int) -> List[Tuple]: ...
    def buscar_estudiante_por_cedula(self, chat_id: int, cedula: str) -> Optional[Tuple]: ...
    def eliminar_estudiantes_grupo(self, chat_id: int) -> None: ...
    def registrar_miembro_telegram(self, chat_id: int, user_id: int, first_name: str, last_name: str, username: str) -> None: ...
    def obtener_miembros_telegram(self, chat_id: int) -> List[Tuple]: ...
    def agregar_pendiente_verificacion(self, user_id: int, chat_id: int, nombre_telegram: str, fecha_limite: str, nombre_oficial: str = "") -> None: ...
    def obtener_pendientes_activos(self) -> List[Tuple]: ...
    def resolver_pendiente(self, user_id: int, chat_id: int, estado: int) -> None: ...
    def registrar_grupo(self, chat_id: int, nombre: str, profesor_id: int) -> None: ...
    def obtener_grupos_profesor(self, profesor_id: int) -> List[Tuple[int, str]]: ...
    def obtener_todos_los_grupos(self) -> List[Tuple[int, str]]: ...
    def es_grupo_registrado(self, chat_id: int) -> bool: ...
    def es_grupo_de_profesor(self, chat_id: int, profesor_id: int) -> bool: ...

class AIAdapterInterface(Protocol):
    def estructurar_texto_formal(self, texto: str) -> str: ...
    def transcribir_y_estructurar(self, texto: str) -> str: ...
    def generar_minuta_apa(self, contenido: str, formato: str) -> str: ...
    def interpretar_intencion(self, mensaje: str) -> str: ...
    def detectar_contenido_inapropiado(self, mensaje: str) -> str: ...
    def responder_conversacion(self, mensaje: str, contexto: str = "") -> str: ...
